-- 코드를 입력하세요
SELECT p.PRODUCT_CODE,
    SUM(p.PRICE * s.SALES_AMOUNT) as SALES
FROM PRODUCT as p JOIN OFFLINE_SALE as s ON p.PRODUCT_ID = s.PRODUCT_ID
GROUP BY p.PRODUCT_ID
ORDER BY SALES desc, p.PRODUCT_CODE asc

