-- 코드를 작성해주세요
SELECT CONCAT(QUARTER(DIFFERENTIATION_DATE),'Q') as 'QUARTER',
    count(*) as 'ECOLI_COUNT'
FROM ECOLI_DATA
GROUP BY QUARTER(DIFFERENTIATION_DATE)
ORDER BY QUARTER(DIFFERENTIATION_DATE)