-- 코드를 입력하세요
SELECT u.USER_ID as USER_ID, u.NICKNAME, SUM(b.PRICE) as TOTAL_PRICE
FROM USED_GOODS_BOARD as b JOIN USED_GOODS_USER as u
ON b.WRITER_ID = u.USER_ID
WHERE b.STATUS='DONE'
GROUP BY u.USER_ID,u.NICKNAME
HAVING (SUM(b.PRICE) >= 700000)
ORDER BY SUM(b.PRICE) asc
